LANGUAGE_STRINGS = {
    "Chinese": {
        "settings_title": "设置",
        "about_section": "关于",
        "about_text": "关于 L4D2 Server OptiBrowser",
        "version": "版本: {current_version}",
        "new_version": "检测到新版本",
        "feature_modules": "功能模块",
        "dashboard": "仪表盘",
        "dashboard_set": "仪表盘:",
        "dashboard_desc": "服务器状态监控仪表盘，提供在线服务器和玩家占用率的可视化统计",
        "filter_controls": "筛选控件:",
        "filter_desc": "显示服务器筛选控件，支持按空房、有人房、超时服务器等进行筛选",
        "map_format": "地图格式:",
        "map_format_desc": "将已收录的地图显示格式从'换图代码'改为'中文名 [换图代码]'格式",
        "enabled": "已启用",
        "disabled": "已禁用",
        "ui_theme": "界面主题",
        "theme_desc": "选择应用程序的视觉主题风格",
        "theme": "主题:",
        "font": "字体:",
        "window_style": "窗口:",
        "preview": "预览:",
        "example_button": "示例按钮",
        "example_text": "示例文本",
        "example_checkbox": "示例复选框",
        "language": "语言:",
        "language_confirm": "语言",
        "language_desc": "选择应用程序的显示语言",
        "restart_required": "需要重启应用以应用此设置",
        "about": "关于",
        "confirm": "确定",
        "confirm_1": "确认",
        "cancel": "取消",
        "author": "作者：竹烨oО柠檬茶 / Zhrradiant LemonTea",
        "message": "留言：免费工具，方便自己查服，希望也能帮到你 :)",
        "internet": "互联网",
        "custom_page": "自定义{page_num}",
        "history": "历史记录",
        "settings": "设置",
        "workshop_parser": "工坊链接解析",
        "map_list": "三方图列表",
        "block_list": "屏蔽列表",
        "query_server_status": "查询服务器状态",
        "get_server_list": "获取服务器列表",
        "ready": "就绪",
        "region": "区域",
        "cloud": "云端",
        "region_query": "区域查询",
        "cloud_fetch": "云端获取",
        "get_region_servers": "获取区域服务器",
        "get_from_cloud": "从云端获取",
        "add_server": "添加服务器",
        "delete_server": "删除服务器",
        "page_config": "页面配置",
        "server_details": "服务器详情",
        "join_server": "加入服务器",
        "copy_connect_command": "复制连接命令",
        "auto_join": "自动加入（有空位时）",
        "favorite_server": "收藏该服务器",
        "favorite_same_ip": "收藏同一IP服务器",
        "block_server_text": "屏蔽服务器",
        "player_name": "玩家名称",
        "score": "分数",
        "online_time": "在线时间",
        "querying": "查询中...",
        "connection_failed": "连接失败",
        "timeout": "超时",
        "unknown": "未知",
        "none": "无",
        "engine_status": "引擎状态",
        "stable": "稳定",
        "standard": "标准",
        "fast": "快速",
        "aggressive": "暴力",
        "confirm_delete": "确认删除",
        "delete_page": "删除页面",
        "delete_page_confirm": "确定要永久删除页面 '{page_name}' 吗？\n该操作不可恢复！",
        "page_name_empty": "页面名称不能为空",
        "page_name_exists": "该页面名称已存在",
        "cannot_rename_history": "无法重命名历史记录页面",
        "cannot_delete_history": "无法删除历史记录页面",
        "current_order": "当前顺序：{current}/{total}",
        "move_up": "↑上移",
        "move_down": "↓下移",
        "servers_loaded_zero": "已装载0服务器",
        "servers_loaded": "已装载{count}服务器",
        "querying_status": "正在查询（{completed}/{total}）",
        "online_count": "查询完成，在线 {online_count} 个",
        "online_count_1": "开始查询 {queried_count}/{total_servers} | 在线 {online_count}",
        "no_servers_to_query": "没有可查询的服务器（可能已被屏蔽）",
        "getting_servers": "正在获取服务器列表...",
        "getting_cloud_servers": "正在从云端获取服务器列表...",
        "servers_fetched": "获取到{count}个服务器",
        "network_error": "网络错误: {msg}",
        "fetch_failed": "获取失败: {msg}",
        "dns_error": "DNS错误",
        "connect_error": "连接错误",
        "copy_failed": "复制失败",
        "init_failed": "初始化失败: {msg}",
        "server_in_blocklist": "该服务器已在屏蔽列表中",
        "block_success": "下次查询时会屏蔽同IP服务器",
        "block_failed": "屏蔽失败: {msg}",
        "file_drop_zone": "文件拖拽区",
        "manual_input_zone": "手动输入区",
        "parse_result": "解析结果",
        "parse_content": "解析内容",
        "confirm_add": "确认添加",
        "drop_file_here": "\n拖拽服务器列表文件至此或手动输入内容",
        "file_loaded": "已加载文件: {filename}",
        "cannot_read_file": "无法读取文件: {msg}",
        "select_region": "选择区域:",
        "select_source": "选择来源:",
        "cloud_weekly": "云端 - 按小时更新",
        "global_region": "全球",
        "us_east": "美国东部",
        "us_west": "美国西部",
        "south_america": "南美",
        "europe": "欧洲",
        "asia": "亚洲",
        "australia": "澳洲",
        "middle_east": "中东",
        "africa": "非洲",
        "from_steam": "从Steam主服务器获取指定区域的服务器列表",
        "from_cloud": "从云端服务器列表文件快速获取服务器地址",
        "map": "地图: {formatted_map}",
        "map_loading": "地图: 加载中...",
        "players_count": "玩家数: {player_count}/{max_players}",
        "refresh_failed": "刷新失败: {msg}",
        "auto_join_enabled": "已启用自动加入功能\n当服务器 {addr} 有空位时将自动连接",
        "block_list_title": "屏蔽列表",
        "ip_address_column": "IP地址",
        "ip_address_column_info": "IP地址: {ip}:{initial_port}",
        "server_name_column": "屏蔽时的服务器名称",
        "block_mode_column": "屏蔽模式",
        "unblock_button": "解除屏蔽",
        "refresh_list_button": "刷新列表",
        "port_config_title": "端口屏蔽配置",
        "block_mode_label": "屏蔽模式:",
        "all_ports_mode": "全端口",
        "single_port_mode": "仅此端口",
        "custom_port_mode": "自定义端口",
        "custom_rules_label": "自定义端口规则（每行一个规则）:",
        "port_rules_example": "25565 (屏蔽25565端口) 25565-25569 (屏蔽25565到25569整个范围的端口) 最大值65535",
        "save_button": "保存",
        "cancel_button": "取消",
        "error_title": "错误",
        "custom_mode_requires_rules": "自定义模式需要至少一个端口规则",
        "invalid_port_range_format": "无效的端口范围格式: {rule}",
        "port_range_out_of_bounds": "端口范围超出有效范围: {rule}",
        "port_range_start_greater": "端口范围起始值大于结束值: {rule}",
        "port_range_invalid_chars": "端口范围包含非数字字符: {rule}",
        "port_out_of_bounds": "端口号超出有效范围: {rule}",
        "port_invalid_chars": "端口号包含非数字字符: {rule}",
        "dashboard_window_title": "服务器状态仪表盘",
        "dashboard_main_title": "服务器状态监控",
        "server_status_section": "服务器状态",
        "active_servers_text": "活跃服务器",
        "player_status_section": "玩家状态",
        "online_players_text": "在服玩家",
        "close_button": "关闭",
        "filter_label": "筛选:",
        "filter_empty": "空房",
        "filter_occupied": "有人",
        "filter_hide_timeout": "隐藏超时",
        "map_list_title": "第三方地图列表",
        "map_details_title": "地图详情",
        "image_loading": "图片加载中...",
        "image_load_failed": "图片加载失败",
        "no_map_preview": "该地图暂无浏览图",
        "download_link_note": "注：下载链接仅供参考，能否成功联机需以服务器端的实际版本为准",
        "invalid_workshop_url": "无效的工坊链接",
        "get_collection_failed_network": "获取合集信息失败，请检查是否可以连接Steam网络",
        "get_item_details_failed_network": "获取物品详情失败，请检查是否可以连接Steam网络",
        "workshop_parser_title": "工坊链接解析",
        "parse_button": "解析",
        "ready_status": "就绪",
        "parsing_collection": "正在解析链接...",
        "found_items_loading": "找到{count}个物品，正在获取详情...",
        "parse_complete_success": "解析完成，",
        "parse_complete_partial_1": "成功解析 {success_count} 个",
        "parse_complete_partial_2": "失败 {error_count} 个",
        "loading_image": "加载中...",
        "copy_workshop_links": "复制{count}个工坊链接",
        "open_workshop_pages": "打开{count}个工坊页面",
        "copy_download_links": "复制{count}个下载链接",
        "open_download_pages": "打开{count}个下载页面",
        "no_download": "无",
        "click_to_download": "[点击此处下载]",
        "input_workshop_url": "请输入Steam工坊合集链接",
        "parse_failed": "解析失败: {error}",
        "partial_failed": "{error_count}个物品详情获取失败，请检查是否可以连接Steam网络",
        "copy_failed_workshop": "复制失败",
        "column_ip": "IP地址",
        "column_vac": "VAC",
        "column_name": "服务器名称",
        "column_game": "游戏",
        "column_map": "当前地图",
        "column_players": "玩家数量",
        "column_latency": "工具延迟",
        "column_keywords": "标签",
        "column_chinese_name": "中文名 (仅参考)",
        "column_display_name": "地图大厅展示名",
        "column_map_code": "换图代码 (按章节顺序)",
        "column_download_link": "地图下载链接 (仅参考)",
        "column_map_identifier": "地图文件识别名",
        "column_title": "物品名称",
        "column_created": "创建时间",
        "column_updated": "更新时间",
        "column_url": "下载",
        "column_preview": "浏览图",
        "stop_server_query": "停止服务器查询",
        "remove_selected_items": "移除选中的 {count} 个条目",
        "copy_player_names": "复制玩家名称",
        "add_to_page": "添加到 {page}",
        "copy_link": "复制链接",
        "open_in_browser": "浏览器打开",
        "parse_workshop_link": "解析工坊链接",
        "copy_col_name": "复制 {col_name}",
        "player_info_window_title": "玩家信息",
        "player_info_main_title": "玩家信息统计",
        "player_stats_section": "玩家统计",
        "player_list_section": "玩家列表",
        "total_players": "总玩家数:",
        "total_servers_with_players": "有玩家的服务器数:",
        "play_time": "在线时间",
        "servers_count": "服务器数",
        "player_details": "玩家详情",
        "total_play_time": "在线时间:",
        "servers_played_on": "相关的服务器数:",
        "servers_list": "服务器列表:",
        "player_info_tooltip_text": "相关的服务器数: {count}\n\n服务器列表:\n",
        "player_info": "玩家信息:",
        "player_info_desc": "提供当前页面服务器中的玩家信息统计，包括玩家名称和在线时间",
        "font_preview_title": "字体预览",
        "font_preview_current": "当前预览: {font_name}",
        "font_preview_default": "当前预览: Default (系统默认字体)",
        "font_preview_restart_hint": "点击确定将关闭程序以应用此字体",
        "window_style_preview_title": "窗口样式预览",
        "window_style_preview_current": "当前预览: {style} 样式",
        "window_style_preview_restart_hint": "点击确定将关闭程序以应用此样式",
        "workshop_hotkey": "工坊快捷键",
        "workshop_hotkey_desc": "设置快捷键，按下时自动解析选中的工坊链接",
        "hotkey": "快捷键:",
        "record_hotkey": "录制",
        "press_hotkey": "按下快捷键...",
        "recording": "录制中...",
        "set": "已设置",
        "not_set": "未设置",
        "system_tray": "系统托盘:",
        "tray_desc": "启用后关闭窗口时最小化到系统托盘，单击托盘图标可恢复显示",
        "startup": "开机启动:",
        "startup_desc": "启用后系统启动时自动运行程序，如果开启了托盘功能则会隐藏启动",
        "success": "成功",
        "block_selected_servers": "屏蔽选中的 {count} 个条目",
        "block_selected_success": "成功屏蔽 {success_count} 个条目\n同ip条目不会重复添加\n下次查询时会屏蔽同IP服务器",
        "filter_custom": "自定义规则",
        "custom_filter_title": "筛选自定义规则",
        "custom_filter_mode": "筛选模式:",
        "custom_filter_show": "显示",
        "custom_filter_hide": "隐藏",
        "custom_filter_rules_desc": "自定义规则（每行一个关键词）:",
        "custom_filter_example": "示例: 输入'合作'将筛选任意列中包含'合作'的服务器",
        "steam_api_fetch": "Steam API 获取",
        "from_steam_api": "通过 Steam Web API 获取服务器列表（需要 API 密钥）",
        "api_key": "API 密钥:",
        "api_key_required": "请输入 Steam Web API 密钥",
        "get_from_api": "通过 API 获取",
        "getting_api_servers": "正在通过 Steam API 获取服务器列表...",
        "api_servers_fetched": "通过 Steam API 获取到 {count} 个服务器",
        "api_key_invalid": "API 密钥无效或无权访问",
        "api_key_unauthorized": "API 密钥未经授权",
        "api_http_error": "HTTP 错误: {code}",
        "api_response_invalid": "API 响应格式无效",
        "api_fetch_failed": "获取失败: {msg}",
        "remember_key": "记住密钥",
        "item_unavailable": "工坊物品不可用或已被移除",
        "get_multiple_items_failed": "批量获取物品详情失败: {error}",
        "no_items_found": "未找到任何工坊物品",
        "parsing_link": "正在解析链接..."
    },
    "English": {
        "settings_title": "Settings",
        "about_section": "About",
        "about_text": "About L4D2 Server OptiBrowser",
        "version": "Version: {current_version}",
        "new_version": "New version detected",
        "feature_modules": "Feature Modules",
        "dashboard": "Dashboard",
        "dashboard_set": "Dashboard:",
        "dashboard_desc": "Server status monitoring dashboard, providing visual statistics of online servers and player occupancy",
        "filter_controls": "Filter Controls:",
        "filter_desc": "Display server filter controls, support filtering by empty rooms, occupied rooms, timeout servers, etc.",
        "map_format": "Map Format:",
        "map_format_desc": "Change the display format of collected maps from 'Map Change Code' to 'Lobby Display Name [Map Change Code]' format",
        "enabled": "Enabled",
        "disabled": "Disabled",
        "ui_theme": "UI Theme",
        "theme_desc": "Select the visual theme style of the application",
        "theme": "Theme:",
        "font": "Font:",
        "window_style": "Window:",
        "preview": "Preview:",
        "example_button": "Example Button",
        "example_text": "Example Text",
        "example_checkbox": "Example Checkbox",
        "language": "Language:",
        "language_confirm": "Language",
        "language_desc": "Select the display language of the application",
        "restart_required": "Restart required to apply this setting",
        "about": "About",
        "confirm": "Confirm",
        "confirm_1": "Confirm",
        "cancel": "Cancel",
        "author": "Author: Zhrradiant LemonTea / 竹烨oО柠檬茶",
        "message": "Message: Free tool, convenient for checking servers, hope it can help you too :)",
        "internet": "Internet",
        "custom_page": "Custom {page_num}",
        "history": "History",
        "settings": "Settings",
        "workshop_parser": "Workshop Link Parser",
        "map_list": "Custom Map List",
        "block_list": "Block List",
        "query_server_status": "Query Server Status",
        "get_server_list": "Get Server List",
        "ready": "Ready",
        "region": "Region",
        "cloud": "Cloud",
        "region_query": "Region Query",
        "cloud_fetch": "Cloud Fetch",
        "get_region_servers": "Get Region Servers",
        "get_from_cloud": "Get from Cloud",
        "add_server": "Add Server",
        "delete_server": "Delete Server",
        "page_config": "Page Configuration",
        "server_details": "Server Details",
        "join_server": "Join Server",
        "copy_connect_command": "Copy Connect Command",
        "auto_join": "Auto Join (when slot available)",
        "favorite_server": "Favorite this Server",
        "favorite_same_ip": "Favorite Same IP Servers",
        "block_server_text": "Block Server",
        "player_name": "Player Name",
        "score": "Score",
        "online_time": "Online Time",
        "querying": "Querying...",
        "connection_failed": "Connection Failed",
        "timeout": "Timeout",
        "unknown": "Unknown",
        "none": "None",
        "engine_status": "Engine Status",
        "stable": "Stable",
        "standard": "Standard",
        "fast": "Fast",
        "aggressive": "Aggressive",
        "confirm_delete": "Confirm Delete",
        "delete_page": "Delete Page",
        "delete_page_confirm": "Are you sure you want to permanently delete page '{page_name}'?\nThis operation cannot be undone!",
        "page_name_empty": "Page name cannot be empty",
        "page_name_exists": "This page name already exists",
        "cannot_rename_history": "Cannot rename history page",
        "cannot_delete_history": "Cannot delete history page",
        "current_order": "Current order: {current}/{total}",
        "move_up": "↑Move Up",
        "move_down": "↓Move Down",
        "servers_loaded_zero": "Loaded 0 servers",
        "servers_loaded": "Loaded {count} servers",
        "querying_status": "Querying ({completed}/{total})",
        "online_count": "Query completed, {online_count} online",
        "online_count_1": "Started query {queried_count}/{total_servers} | Online {online_count}",
        "no_servers_to_query": "No servers to query (may be blocked)",
        "getting_servers": "Getting server list...",
        "getting_cloud_servers": "Getting server list from cloud...",
        "servers_fetched": "Fetched {count} servers",
        "network_error": "Network error: {msg}",
        "fetch_failed": "Fetch failed: {msg}",
        "dns_error": "DNS error",
        "connect_error": "Connection error",
        "copy_failed": "Copy failed",
        "init_failed": "Initialization failed: {msg}",
        "server_in_blocklist": "This server is already in the block list",
        "block_success": "Same IP servers will be blocked in the next query",
        "block_failed": "Block failed: {msg}",
        "file_drop_zone": "File Drop Zone",
        "manual_input_zone": "Manual Input Zone",
        "parse_result": "Parse Result",
        "parse_content": "Parse Content",
        "confirm_add": "Confirm Add",
        "drop_file_here": "\nDrag server list file here or manually input content",
        "file_loaded": "File loaded: {filename}",
        "cannot_read_file": "Cannot read file: {msg}",
        "select_region": "Select Region:",
        "select_source": "Select Source:",
        "cloud_weekly": "Cloud - Hourly Update",
        "global_region": "Global",
        "us_east": "US East",
        "us_west": "US West",
        "south_america": "South America",
        "europe": "Europe",
        "asia": "Asia",
        "australia": "Australia",
        "middle_east": "Middle East",
        "africa": "Africa",
        "from_steam": "Get server list for specified region from Steam master server",
        "from_cloud": "Quickly get server addresses from cloud server list file",
        "map": "Map: {formatted_map}",
        "map_loading": "Map: Loading...",
        "players_count": "Players: {player_count}/{max_players}",
        "refresh_failed": "Refresh failed: {msg}",
        "auto_join_enabled": "Auto join enabled\nWill automatically connect when server {addr} has available slots",
        "block_list_title": "Block List",
        "ip_address_column": "IP Address",
        "ip_address_column_info": "IP Address: {ip}:{initial_port}",
        "server_name_column": "Server Name when Blocked",
        "block_mode_column": "Block Mode",
        "unblock_button": "Unblock",
        "refresh_list_button": "Refresh List",
        "port_config_title": "Port Block Configuration",
        "block_mode_label": "Block Mode:",
        "all_ports_mode": "All Ports",
        "single_port_mode": "This Port Only",
        "custom_port_mode": "Custom Ports",
        "custom_rules_label": "Custom port rules (one rule per line):",
        "port_rules_example": "25565 (block port 25565) 25565-25569 (from 25565 to 25569) Max 65535",
        "save_button": "Save",
        "cancel_button": "Cancel",
        "error_title": "Error",
        "custom_mode_requires_rules": "Custom mode requires at least one port rule",
        "invalid_port_range_format": "Invalid port range format: {rule}",
        "port_range_out_of_bounds": "Port range out of bounds: {rule}",
        "port_range_start_greater": "Port range start greater than end: {rule}",
        "port_range_invalid_chars": "Port range contains non-numeric characters: {rule}",
        "port_out_of_bounds": "Port number out of bounds: {rule}",
        "port_invalid_chars": "Port number contains non-numeric characters: {rule}",
        "dashboard_window_title": "Server Status Dashboard",
        "dashboard_main_title": "Server Status Monitoring",
        "server_status_section": "Server Status",
        "active_servers_text": "Active Servers",
        "player_status_section": "Player Status",
        "online_players_text": "Online Players",
        "close_button": "Close",
        "filter_label": "Filter:",
        "filter_empty": "Empty",
        "filter_occupied": "Occupied",
        "filter_hide_timeout": "Hide Timeout",
        "map_list_title": "Custom Map List",
        "map_details_title": "Map Details",
        "image_loading": "Image loading...",
        "image_load_failed": "Image load failed",
        "no_map_preview": "No preview available for this map",
        "download_link_note": "Note: Download links are for reference only, successful connection depends on the actual version on the server side",
        "invalid_workshop_url": "Invalid workshop URL",
        "get_collection_failed_network": "Failed to get collection information, please check if you can connect to Steam network",
        "get_item_details_failed_network": "Failed to get item details, please check if you can connect to Steam network",
        "workshop_parser_title": "Workshop Link Parser",
        "parse_button": "Parse",
        "ready_status": "Ready",
        "parsing_collection": "Parsing link...",
        "found_items_loading": "Found {count} items, getting details...",
        "parse_complete_success": "Parse completed, ",
        "parse_complete_partial_1": "Successfully parsed {success_count}",
        "parse_complete_partial_2": "Failed {error_count}",
        "loading_image": "Loading...",
        "copy_workshop_links": "Copy {count} workshop links",
        "open_workshop_pages": "Open {count} workshop pages",
        "copy_download_links": "Copy {count} download links",
        "open_download_pages": "Open {count} download pages",
        "no_download": "None",
        "click_to_download": "[Click here to download]",
        "input_workshop_url": "Please enter Steam workshop collection URL",
        "parse_failed": "Parse failed: {error}",
        "partial_failed": "Failed to get details for {error_count} items, please check if you can connect to Steam network",
        "copy_failed_workshop": "Copy failed",
        "column_ip": "IP ADDRESS",
        "column_vac": "VAC",
        "column_name": "SERVERS",
        "column_game": "GAME",
        "column_map": "MAP",
        "column_players": "PLAYERS",
        "column_latency": "TOOL LATENCY",
        "column_keywords": "TAGS",
        "column_chinese_name": "Chinese Name (Reference Only)",
        "column_display_name": "Lobby Display Name",
        "column_map_code": "Map Change Code (by Chapter Order)",
        "column_download_link": "Map Download Link (Reference Only)",
        "column_map_identifier": "Map File Identifier",
        "column_title": "Item Name",
        "column_created": "Created Time",
        "column_updated": "Updated Time",
        "column_url": "Download",
        "column_preview": "Preview",
        "stop_server_query": "Stop Server Query",
        "remove_selected_items": "Remove selected {count} items",
        "copy_player_names": "Copy Player Names",
        "add_to_page": "Add to {page}",
        "copy_link": "Copy Link",
        "open_in_browser": "Open in Browser",
        "parse_workshop_link": "Parse Workshop Link",
        "copy_col_name": "Copy {col_name}",
        "player_info_window_title": "Player Information",
        "player_info_main_title": "Player Information Statistics",
        "player_stats_section": "Player Statistics",
        "player_list_section": "Player List",
        "total_players": "Total Players:",
        "total_servers_with_players": "Servers with Players:",
        "play_time": "Online Time",
        "servers_count": "Number of Servers",
        "player_details": "Player Details",
        "total_play_time": "Online Time:",
        "servers_played_on": "Related Servers:",
        "servers_list": "Server List:",
        "player_info_tooltip_text": "Related Servers: {count}\n\nServer List:\n",
        "player_info": "Player Information:",
        "player_info_desc": "Provides statistical information about players on the current page server, including player names and online time",
        "font_preview_title": "Font Preview",
        "font_preview_current": "Current Preview: {font_name}",
        "font_preview_default": "Current Preview: Default (System Default Font)",
        "font_preview_restart_hint": "Click confirm to close the program and apply this font",
        "window_style_preview_title": "Window Style Preview",
        "window_style_preview_current": "Current Preview: {style} Style",
        "window_style_preview_restart_hint": "Click confirm to close the program and apply this style",
        "workshop_hotkey": "Workshop Hotkey",
        "workshop_hotkey_desc": "Set hotkey to automatically parse selected workshop links",
        "hotkey": "Hotkey:",
        "record_hotkey": "Record",
        "press_hotkey": "Press hotkey...",
        "recording": "Recording...",
        "set": "Set",
        "not_set": "Not Set",
        "system_tray": "System Tray:",
        "tray_desc": "Minimize to system tray when closing window, click tray icon to restore",
        "startup": "Startup:",
        "startup_desc": "Automatically run the program at system startup, will start minimized if tray is enabled",
        "success": "Success",
        "block_selected_servers": "Block selected {count} items",
        "block_selected_success": "Successfully blocked {success_count} items\nDuplicate IP items will not be added\nSame IP servers will be blocked in the next query",
        "filter_custom": "Custom Rules",
        "custom_filter_title": "Filter Custom Rules",
        "custom_filter_mode": "Filter Mode:",
        "custom_filter_show": "Show",
        "custom_filter_hide": "Hide",
        "custom_filter_rules_desc": "Custom rules (one keyword per line):",
        "custom_filter_example": "Example: Enter 'coop' to filter servers containing 'coop' in any column",
        "steam_api_fetch": "Steam API Fetch",
        "from_steam_api": "Get server list via Steam Web API (API key required)",
        "api_key": "API Key:",
        "api_key_required": "Please enter Steam Web API key",
        "get_from_api": "Get via API",
        "getting_api_servers": "Getting server list via Steam API...",
        "api_servers_fetched": "Fetched {count} servers via Steam API",
        "api_key_invalid": "API key is invalid or no access",
        "api_key_unauthorized": "API key unauthorized",
        "api_http_error": "HTTP error: {code}",
        "api_response_invalid": "API response format invalid",
        "api_fetch_failed": "Fetch failed: {msg}",
        "remember_key": "Remember Key",
        "item_unavailable": "Workshop item unavailable or removed",
        "get_multiple_items_failed": "Failed to get multiple item details: {error}",
        "no_items_found": "No workshop items found",
        "parsing_link": "Parsing link..."
    }
}

import os
import json

CONFIG_FILE = "server_checker_config.json"


def load_language_from_config():
    """从配置文件加载语言设置"""
    global CURRENT_LANGUAGE
    try:
        if os.path.exists(CONFIG_FILE):
            with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
                config = json.load(f)

            if 'language' in config:
                lang_code = config['language']
                if lang_code in LANGUAGE_STRINGS:
                    CURRENT_LANGUAGE = lang_code
                    return True
    except Exception as e:
        print(f"加载语言配置失败: {str(e)}")

    return False


# 应用启动时立即加载语言配置
load_language_from_config()

# 当前语言设置（默认为中文）
CURRENT_LANGUAGE = "Chinese"

def set_language(lang_code):
    """设置当前语言"""
    global CURRENT_LANGUAGE
    if lang_code in LANGUAGE_STRINGS:
        CURRENT_LANGUAGE = lang_code
    return get_string

def get_string(key, default=None):
    """获取本地化字符串"""
    return LANGUAGE_STRINGS.get(CURRENT_LANGUAGE, {}).get(key, default or key)

def get_available_languages():
    """获取可用的语言列表"""
    return list(LANGUAGE_STRINGS.keys())